---
title: "Projeto de Análise Exploratória de Dados com R"
---

Com o objetivo de praticar os conceitos apresentados no curso, recomendamos que as pessoas participantes realizem um projeto de análise exploratória de dados paralelamente às aulas. Este projeto permitirá que você consolide o aprendizado adquirido, explorando dados reais e aplicando as ferramentas de análise discutidas em aula.

Aproveite o projeto para aplicar os conceitos apresentados no curso e para explorar novas funcionalidades do R. **Ao se deparar com uma dúvida, não esqueça de anotar e perguntar durante as aulas para os monitores**. A equipe do curso está disponível para auxiliar com dúvidas sobre o projeto até a data final do curso.

Os passos a seguir podem te ajudar a organizar o projeto de análise exploratória de dados:

1. **Escolha um conjunto de dados**: Você pode escolher um conjunto de dados de sua preferência. Caso não tenha um conjunto de dados em mente, sugerimos que escolha um dos conjuntos de dados disponíveis nos seguintes pacotes:

    - [sidrar](https://cran.r-project.org/web/packages/sidrar/vignettes/Introduction_to_sidrar.html): Acesso aos dados disponíveis no SIDRA - Sistema IBGE de Recuperação Automática.
    - [censobr](https://ipeagit.github.io/censobr/): Dados de censos demográficos brasileiros.
    - [ipeadatar](https://cran.r-project.org/web/packages/ipeadatar/index.html): Acesso aos dados disponibilizados no [Ipeadata](http://www.ipeadata.gov.br/Default.aspx).
    - [flightsbr](https://github.com/ipeaGIT/flightsbr): Dados de vôos no Brasil.
    - [PNADcIBGE](https://cran.r-project.org/web/packages/PNADcIBGE/index.html): Dados da PNAD Contínua do IBGE.
    - [microdatasus](https://rfsaldanha.github.io/microdatasus/): Acesso aos microdados do DataSUS.    
    
1. **Crie um projeto no RStudio**: Crie um projeto no RStudio para armazenar os códigos e arquivos do projeto. Esse procedimento será descrito na aula [Conhecendo o R e o RStudio](01_r_rstudio.qmd). 

1. **Importe os dados**: Importe o conjunto de dados escolhido para o R. Esse procedimento será descrito na aula [Importando dados](03_importacao.qmd).

1. **Objetivo da análise**: Defina o objetivo da análise exploratória de dados. Quais são as perguntas que você deseja responder a partir desta base de dados?

1. **Descreva o conjunto de dados brutos**: Faça uma breve descrição do conjunto de dados escolhido. Qual é a unidade amostral (o que cada linha significa)? Quais são as variáveis presentes? Quais são os tipos de variáveis? Você pode incluir tabelas ou gráficos para facilitar a visualização das variáveis e sua distribuição. O que precisa ser feito para deixar a tabela "limpa", ou seja, pronta para a análise?

1. **Limpeza dos dados**: Utilize o que você aprendeu na etapa passada para limpar o conjunto de dados. Isso pode incluir lidar com dados ausentes, remover outliers ou inconsistências. A aula [Transformando dados](05_transformacao.qmd) será útil nessa etapa.

1. **Realize a análise exploratória de dados**: Utilize os conceitos apresentados no curso para realizar a análise exploratória de dados do conjunto escolhido. Lembre-se do objetivo que você definiu anteriormente e busque responder às perguntas que você levantou. Inclua gráficos e tabelas para apresentar os resultados e escreva suas interpretações ao longo do processo. As aulas [Analisando dados](07_analise.qmd) e [Visualizando dados](08_visualizacao.qmd) serão úteis nessa etapa.

1. **Próximos passos**: Você pode apresentar os resultados para outras pessoas envolvidas no curso (participantes, ministrantes, monitores) e solicitar feedbacks.