# Inspirado em: 
# - https://github.com/ipeaGIT/censobr_oficina_abep_2024/blob/main/_quarto.yml
# - https://github.com/ipeaGIT/access_workshop_eit_2024/blob/main/_quarto.yml
project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

lang: pt 

website:
  title: "Introdução à análise de dados no R"
  site-url: "https://ipeadata-lab.github.io/curso_r_intro_202409"
  repo-url: "https://github.com/ipeadata-lab/curso_r_intro_202409"
  sidebar:
    style: "docked"
    search: true
    tools: 
      - icon: github
        text: github
        href: https://github.com/ipeadata-lab/curso_r_intro_202409
    contents:
      - section: "Pré-curso"
        contents:
        - index.qmd
        - 00_instrucoes_pre_curso.qmd      
        - 00_projeto_eda.qmd
      - section: "Conceitos básicos"
        contents:      
        - 01_r_rstudio.qmd
        - 01_1_rproj.qmd        
        - 02_conceitos_basicos_r.qmd
        
      - section: "Etapas em uma análise de dados"
        contents:           
        - 00_intro_etapas_analise.qmd
        - 03_importacao.qmd
        - 04_conhecendo.qmd
        - 05_transformacao.qmd
        - 06_analise_exploratoria.qmd
        - 07_visualizacao.qmd
        - 08_regressao_linear.qmd        
      - section: "Explorando o Censo Demográfico"
        contents:
        - 09_censobr_intro.qmd
        - 10_censobr_conceitos.qmd
        - 11_censobr_microdados.qmd
        - 12_censobr_agregados_setores.qmd
        - 13_censobr_documentacao.qmd
      - section: "Data Lake do Ipea"
        contents:
        - 14_infra_ipea.qmd
        - 15_ipeadatalake.qmd
      - section: "Anexos"
        contents:        
        - 00_erros_frequentes.qmd

page-navigation: true

page-footer: 
  border: true
  left: "Copyright 2024, Beatriz Milz e IPEA/COCD" 
  right: 
    - icon: github
      href: https://github.com/ipeadata-lab/curso_r_intro_202409s


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 5
    link-external-icon: false
    link-external-newwindow: true

bibliography: references.bib

editor: source
