---
title: "Introdução à análise de dados no R"
subtitle: "Utilizando dados públicos brasileiros"

---

## Introdução ao material

Este site apresenta o material de apoio para o curso **"Introdução à análise de dados no R"**, oferecido em 2024.
O curso será realizado de forma remota, com aulas ao vivo e atividades práticas.

:::{.callout-important}
Recomendamos que todas as pessoas participantes instalem o R e o RStudio antes do início do curso.
Para isso, siga as instruções disponíveis na página [Instruções de instalação](00_instrucoes_pre_curso.qmd).

Caso tenha alguma dificuldade, entre em contato com a equipe do curso o quanto antes.
:::



## Sobre a equipe do curso

**Beatriz Milz** <br>
*Pesquisadora Colaboradora | Estágio pós-doutoral* <br>
[Laboratório de Planejamento Territorial (LaPlan)](https://laplan.pesquisa.ufabc.edu.br/) - Universidade Federal do ABC (UFABC)
[Email](mailto:milz.bea@gmail.com) | [GitHub](https://github.com/beatrizmilz) | [LinkedIn](https://www.linkedin.com/in/beatrizmilz/) |
[ResearchGate](https://www.researchgate.net/profile/Beatriz-Milz) | [Currículo Lattes](http://lattes.cnpq.br/5150665880581477) | [Orcid](https://orcid.org/0000-0002-3064-4486)


**Pedro Cavalcanti Gonçalves Ferreira** <br>
*Coordenação de Ciência de Dados - COCD* <br>
Instituto de Pesquisa Econômica Aplicada (Ipea) <br>
[GitHub](https://github.com/cavalcanti1985) |
[LinkedIn](https://www.linkedin.com/in/pedro-cavalcanti-256806235/) |
[Currículo Lattes](http://lattes.cnpq.br/1425315335920636) |
[Orcid](https://orcid.org/0000-0002-8540-1860) 



**Rafael H. M. Pereira** <br> *Coordenador de Ciência de Dados* <br> Instituto de Pesquisa Econômica Aplicada (Ipea) <br> [Website](https://www.urbandemographics.org/about/) | [Google Scholar](https://scholar.google.com.br/citations?user=dbRivsEAAAAJ&hl)
| [Twitter](https://x.com/UrbanDemog) | [Linkedin](https://www.linkedin.com/in/rafael-h-m-pereira/) | 



## Sobre este material

Esse material está disponível sob a [licença CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).